from enum import Enum

class Action(str, Enum):
    PING                 = "PING"
    PONG                 = "PONG"
    REQUEST_DATA         = "REQUEST_DATA"
    RETURN_DATA          = "RETURN_DATA"
    DELEGATE_TASK        = "DELEGATE_TASK"
    TASK_RESULT          = "TASK_RESULT"
    REQUEST_QUOTE        = "REQUEST_QUOTE"
    RETURN_QUOTE         = "RETURN_QUOTE"
    PROPOSE_TRANSACTION  = "PROPOSE_TRANSACTION"
    ACCEPT_TRANSACTION   = "ACCEPT_TRANSACTION"
    REJECT_TRANSACTION   = "REJECT_TRANSACTION"
    REQUEST_HUMAN_AUTH   = "REQUEST_HUMAN_AUTH"
    HUMAN_AUTH_RESPONSE  = "HUMAN_AUTH_RESPONSE"
    ERROR                = "ERROR"
    DISCONNECT           = "DISCONNECT"

class Capability(str, Enum):
    READ_BANK_BALANCE   = "READ_BANK_BALANCE"
    REQUEST_QUOTE       = "REQUEST_QUOTE"
    COMPARE_RATES       = "COMPARE_RATES"
    DELEGATE_TASK       = "DELEGATE_TASK"
    REQUEST_DATA        = "REQUEST_DATA"
    RETURN_DATA         = "RETURN_DATA"
    PROPOSE_TRANSACTION = "PROPOSE_TRANSACTION"
    REQUEST_HUMAN_AUTH  = "REQUEST_HUMAN_AUTH"

DEFAULT_REGISTRY_URL = "https://registry.aap.dev"
AAP_VERSION = "1.0"
MESSAGE_TTL_SECONDS = 30
